import React from "react";
export type AnalysisType = "fullAngleMBD" | "fullAngle" | "fullAngleCumulative" | "partialImpact";
export type PartialImpactMode = "default" | "txt";
export type AngleSource = "lhs" | "preMBD" | "fromMBD" | "preFA" | "fromFA";
export type HeightSource = "const" | "lhs";
export type DropType = "steelPlate" | "concreteBrick" | "custom";
export type CumDirection = `F${1 | 2 | 3 | 4 | 5 | 6}` | `E${1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12}` | `C${1 | 2 | 3 | 4 | 5 | 6 | 7 | 8}`;
export interface ScenarioRow {
    id: string;
    name: string;
    fileName?: string;
    file?: File;
    objFileName?: string;
    objFile?: File;
    analysisType: AnalysisType;
    params?: {
        angleSource?: AngleSource;
        angleSourceId?: string;
        angleSourceFileName?: string;
        angleSourceFile?: File;
        heightSource?: HeightSource;
        heightConstValue?: number;
        heightLhsMin?: number;
        heightLhsMax?: number;
        dropType?: DropType;
        dropTypeCustom?: string;
        mbdCount?: number;
        faTotal?: number;
        includeFace6?: boolean;
        includeEdge12?: boolean;
        includeCorner8?: boolean;
        preMbdCount?: number;
        preFaTotal?: number;
        cumRepeatCount?: 2 | 3 | 4 | 5;
        cumDOECount?: number;
        cumDirections?: CumDirection[];
        cumDirectionsGrid?: CumDirection[][];
        piMode?: PartialImpactMode;
        piTxtName?: string;
        piTxtFile?: File;
    };
}
declare const SimulationAutomationComponent: React.FC;
export default SimulationAutomationComponent;
