#!/bin/bash

echo "========================================"
echo "🔍 /usr/local/slurm/etc/slurm.conf 확인"
echo "========================================"
echo ""

SLURM_CONF="/usr/local/slurm/etc/slurm.conf"

# 1. 파일 존재 확인
echo "1️⃣ 파일 존재 확인:"
if [ -f "$SLURM_CONF" ]; then
    echo "   ✅ 파일 존재"
    ls -lh "$SLURM_CONF"
else
    echo "   ❌ 파일이 없습니다"
    exit 1
fi
echo ""

# 2. RebootProgram 설정 확인
echo "2️⃣ RebootProgram 설정 확인:"
if grep -q "^RebootProgram" "$SLURM_CONF" 2>/dev/null; then
    echo "   ✅ RebootProgram 설정 발견:"
    grep "^RebootProgram" "$SLURM_CONF" | sed 's/^/      /'
else
    echo "   ❌ RebootProgram 설정 없음"
fi

# 주석 처리된 것도 확인
if grep -q "^#.*RebootProgram" "$SLURM_CONF" 2>/dev/null; then
    echo "   ⚠️  주석 처리된 RebootProgram 발견:"
    grep "^#.*RebootProgram" "$SLURM_CONF" | sed 's/^/      /'
fi
echo ""

# 3. Authentication 섹션 확인 (RebootProgram이 들어갈 위치)
echo "3️⃣ Authentication 섹션 확인:"
echo "   (RebootProgram은 이 섹션 아래에 추가해야 함)"
grep -A 5 "^# Authentication\|^#.*Authentication\|^AuthType\|^CryptoType" "$SLURM_CONF" | head -20 | sed 's/^/   /'
echo ""

# 4. 전체 파일 내용 표시
echo "4️⃣ 전체 slurm.conf 내용:"
echo "========================================"
cat "$SLURM_CONF"
echo "========================================"
echo ""

# 5. 파일 수정 권한 확인
echo "5️⃣ 파일 수정 권한 확인:"
if [ -w "$SLURM_CONF" ]; then
    echo "   ✅ 쓰기 권한 있음 (수정 가능)"
else
    echo "   ⚠️  쓰기 권한 없음 (sudo 필요)"
    echo "      소유자: $(stat -c '%U:%G' $SLURM_CONF 2>/dev/null || stat -f '%Su:%Sg' $SLURM_CONF 2>/dev/null)"
fi
echo ""

# 6. 파일이 자동 생성된 것인지 확인
echo "6️⃣ 자동 생성 여부 확인:"
if grep -q "Auto-generated by KooSlurmInstallAutomation" "$SLURM_CONF" 2>/dev/null; then
    echo "   ✅ KooSlurmInstallAutomation으로 생성된 파일"
    echo "   생성 정보:"
    head -5 "$SLURM_CONF" | grep -i "generated\|created" | sed 's/^/      /'
else
    echo "   ⚠️  수동으로 작성되었거나 다른 방법으로 생성됨"
fi
echo ""

# 7. 백업 파일 확인
echo "7️⃣ 백업 파일 확인:"
ls -lh /usr/local/slurm/etc/slurm.conf* 2>/dev/null | sed 's/^/   /'
echo ""

echo "========================================"
echo "✅ 확인 완료!"
echo "========================================"
echo ""
echo "💡 다음 단계:"
echo "   1. RebootProgram이 없다면 추가 필요"
echo "   2. 추가 방법:"
echo "      sudo vim /usr/local/slurm/etc/slurm.conf"
echo "      # Authentication 섹션 아래에 추가:"
echo "      # RebootProgram=/sbin/reboot"
echo "   3. 또는 자동 추가 스크립트 실행"
