#!/bin/bash
# update_cluster_nodes.sh
# YAML의 노드 설정 변경 후 Slurm + Apptainer를 자동으로 업데이트하는 통합 스크립트
#
# 수행 작업:
#   1. YAML에서 NodeName / PartitionName 항목 재생성
#   2. slurm.conf 업데이트 (백업 후 교체)
#   3. 모든 노드에 slurm.conf 배포
#   4. scontrol reconfigure
#   5. (선택) phase8_containers.sh 실행하여 apptainer 이미지 재배포
#
# 사용법:
#   sudo ./update_cluster_nodes.sh [옵션]
#
# 옵션:
#   --config PATH        YAML 설정 파일 (기본값: my_multihead_cluster_2.yaml)
#   --skip-apptainer     Apptainer 이미지 재배포 건너뜀
#   --slurm-only         slurm.conf 업데이트 + reconfigure만 수행
#   --dry-run            실제 변경 없이 결과만 미리 보기
#   -h, --help           도움말 출력

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/my_multihead_cluster_2.yaml"
PHASE8_SCRIPT="${SCRIPT_DIR}/cluster/setup/phase8_containers.sh"

SKIP_APPTAINER=false
SLURM_ONLY=false
DRY_RUN=false

# ─── 색상 출력 ───────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

log_info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
log_success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
log_warning() { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
log_error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; }
log_section() { echo -e "\n${BOLD}━━━ $* ━━━${RESET}"; }
dry_prefix()  { $DRY_RUN && echo -e "${YELLOW}[DRY-RUN]${RESET} " || echo ""; }

# ─── 인자 파싱 ───────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case $1 in
        --config)         CONFIG_FILE="$2"; shift 2 ;;
        --skip-apptainer) SKIP_APPTAINER=true; shift ;;
        --slurm-only)     SLURM_ONLY=true; shift ;;
        --dry-run)        DRY_RUN=true; shift ;;
        -h|--help)
            sed -n '3,18p' "$0" | sed 's/^# \?//'
            exit 0 ;;
        *) log_error "알 수 없는 옵션: $1"; exit 1 ;;
    esac
done

# ─── 사전 확인 ───────────────────────────────────────────────────────────────
[[ ! -f "$CONFIG_FILE" ]] && { log_error "설정 파일을 찾을 수 없습니다: $CONFIG_FILE"; exit 1; }

# slurm.conf 경로 자동 감지
if [[ -f "/usr/local/slurm/etc/slurm.conf" ]]; then
    SLURM_CONF="/usr/local/slurm/etc/slurm.conf"
elif [[ -f "/etc/slurm/slurm.conf" ]]; then
    SLURM_CONF="/etc/slurm/slurm.conf"
else
    log_error "slurm.conf를 찾을 수 없습니다."
    exit 1
fi

SCONTROL=$(command -v scontrol 2>/dev/null || echo "/usr/local/slurm/bin/scontrol")
SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=10 -o BatchMode=yes"

log_section "Cluster Node Update"
log_info "설정 파일  : $CONFIG_FILE"
log_info "slurm.conf : $SLURM_CONF"
$DRY_RUN && log_warning "DRY-RUN 모드 — 실제 변경 없음"

# ─── 1. YAML에서 NodeName / PartitionName 생성 ───────────────────────────────
log_section "Step 1: YAML에서 Slurm 설정 생성"

NEW_ENTRIES=$(python3 << EOPY
import yaml, sys

with open('$CONFIG_FILE') as f:
    config = yaml.safe_load(f)

compute_nodes = config.get('nodes', {}).get('compute_nodes', [])
partitions    = config.get('slurm_config', {}).get('partitions', [])

lines = []

# NodeName 항목
lines.append('# === NodeName definitions (auto-generated by update_cluster_nodes.sh) ===')
for node in compute_nodes:
    hw = node.get('hardware', {})
    parts = [f"NodeName={node['hostname']}"]
    if node.get('ip_address'):
        parts.append(f"NodeAddr={node['ip_address']}")
    parts += [
        f"CPUs={hw.get('cpus', 1)}",
        f"Sockets={hw.get('sockets', 1)}",
        f"CoresPerSocket={hw.get('cores_per_socket', 1)}",
        f"ThreadsPerCore={hw.get('threads_per_core', 1)}",
        f"RealMemory={hw.get('memory_mb', 1024)}",
    ]
    if hw.get('gres'):
        parts.append(f"Gres={hw['gres']}")
    parts.append('State=UNKNOWN')
    lines.append(' '.join(parts))

# PartitionName 항목
lines.append('# === PartitionName definitions (auto-generated by update_cluster_nodes.sh) ===')
for p in partitions:
    default  = 'YES' if p.get('default', False) else 'NO'
    line = f"PartitionName={p['name']} Nodes={p.get('nodes','ALL')} Default={default} MaxTime={p.get('max_time','INFINITE')} State={p.get('state','UP')}"
    if p.get('max_nodes'):
        line += f" MaxNodes={p['max_nodes']}"
    if p.get('exclusive'):
        line += f" Shared={'NO' if p['exclusive'] else 'YES'}"
    lines.append(line)

print('\n'.join(lines))
EOPY
)

echo "$NEW_ENTRIES"
log_success "설정 생성 완료"

# ─── 2. slurm.conf 업데이트 ──────────────────────────────────────────────────
log_section "Step 2: slurm.conf 업데이트"

BACKUP_PATH="${SLURM_CONF}.backup.$(date +%Y%m%d_%H%M%S)"

if $DRY_RUN; then
    log_info "[DRY-RUN] 백업 생성: $BACKUP_PATH"
    log_info "[DRY-RUN] NodeName/PartitionName 줄 교체 후 저장"
else
    sudo cp "$SLURM_CONF" "$BACKUP_PATH"
    log_success "백업 완료: $BACKUP_PATH"

    # 기존 NodeName/PartitionName/auto-generated 주석 줄 제거 후 새 내용 추가
    TMP_CONF=$(mktemp)
    grep -v "^NodeName=\|^PartitionName=\|^# === NodeName\|^# === PartitionName" "$SLURM_CONF" > "$TMP_CONF"
    printf '\n%s\n' "$NEW_ENTRIES" >> "$TMP_CONF"
    sudo cp "$TMP_CONF" "$SLURM_CONF"
    rm "$TMP_CONF"
    log_success "slurm.conf 업데이트 완료"
fi

# ─── 3. 모든 노드에 slurm.conf 배포 ─────────────────────────────────────────
log_section "Step 3: 전 노드 slurm.conf 배포"

ALL_NODES=$(python3 << EOPY
import yaml

with open('$CONFIG_FILE') as f:
    config = yaml.safe_load(f)

nodes = []
# compute_nodes
for n in config.get('nodes', {}).get('compute_nodes', []):
    if n.get('hostname') and n.get('ip_address'):
        nodes.append((n['hostname'], n['ip_address'], n.get('ssh_user', 'koopark')))

# controllers (호스트 제외)
import socket
my_hostname = socket.gethostname()
for n in config.get('nodes', {}).get('controllers', []):
    if n.get('hostname') and n.get('ip_address') and n['hostname'] != my_hostname:
        nodes.append((n['hostname'], n['ip_address'], n.get('ssh_user', 'koopark')))

# 중복 제거
seen = set()
for hostname, ip, user in nodes:
    if hostname not in seen:
        seen.add(hostname)
        print(f"{hostname}|{ip}|{user}")
EOPY
)

DEPLOY_SUCCESS=0
DEPLOY_FAIL=0

while IFS='|' read -r hostname ip user; do
    [[ -z "$hostname" ]] && continue
    log_info "배포 중: $hostname ($ip)"

    if $DRY_RUN; then
        log_info "  [DRY-RUN] scp $SLURM_CONF → ${user}@${ip}:${SLURM_CONF}"
        ((DEPLOY_SUCCESS++))
    else
        REMOTE_CONF="$SLURM_CONF"
        if ssh $SSH_OPTS "${user}@${ip}" "sudo tee '$REMOTE_CONF' > /dev/null" < "$SLURM_CONF" 2>/dev/null; then
            log_success "  ✓ $hostname"
            DEPLOY_SUCCESS=$((DEPLOY_SUCCESS + 1))
        else
            log_warning "  ✗ $hostname — 배포 실패 (slurmd 재시작 시 수동 배포 필요)"
            DEPLOY_FAIL=$((DEPLOY_FAIL + 1))
        fi
    fi
done <<< "$ALL_NODES"

log_info "배포 결과: 성공 ${DEPLOY_SUCCESS}개, 실패 ${DEPLOY_FAIL}개"

# ─── 4. scontrol reconfigure ─────────────────────────────────────────────────
log_section "Step 4: scontrol reconfigure"

if $DRY_RUN; then
    log_info "[DRY-RUN] sudo $SCONTROL reconfigure"
else
    if sudo "$SCONTROL" reconfigure 2>/dev/null; then
        log_success "Slurm 재구성 완료"
    else
        log_warning "scontrol reconfigure 실패 — slurmctld restart 시도"
        sudo systemctl restart slurmctld && log_success "slurmctld 재시작 완료"
    fi

    sleep 2
    log_info "현재 파티션 상태:"
    "$SCONTROL" show partition 2>/dev/null | grep -E "PartitionName|Nodes|State" || true
fi

# ─── 5. Apptainer 이미지 재배포 (phase8) ─────────────────────────────────────
if $SLURM_ONLY; then
    log_info "--slurm-only 옵션: Apptainer 배포 건너뜀"
    log_section "완료"
    exit 0
fi

if $SKIP_APPTAINER; then
    log_info "--skip-apptainer 옵션: Apptainer 배포 건너뜀"
    log_section "완료"
    exit 0
fi

log_section "Step 5: Apptainer 이미지 재배포 (phase8)"

if [[ ! -f "$PHASE8_SCRIPT" ]]; then
    log_warning "phase8_containers.sh를 찾을 수 없습니다: $PHASE8_SCRIPT"
    log_warning "Apptainer 이미지 배포를 건너뜁니다."
else
    if $DRY_RUN; then
        log_info "[DRY-RUN] sudo $PHASE8_SCRIPT --config $CONFIG_FILE"
    else
        sudo "$PHASE8_SCRIPT" --config "$CONFIG_FILE"
    fi
fi

log_section "완료"
log_success "클러스터 노드 업데이트 완료"
echo ""
echo "  slurm.conf 백업: $BACKUP_PATH"
echo "  현재 상태 확인:  $SCONTROL show node"
echo "  파티션 확인:     /usr/local/slurm/bin/sinfo"
