import React from "react";
export type AnalysisType = "fullAngleMBD" | "fullAngle" | "fullAngleCumulative" | "multiRepeatCumulative" | "dropWeightImpact" | "predefinedAttitudes" | "edgeAxisRotation";
export type PartialImpactMode = "default" | "txt";
export type AngleSource = "lhs" | "fromMBD" | "usePrevResult";
export type HeightMode = "const" | "lhs";
export type SurfaceType = "steelPlate" | "pavingBlock" | "concrete" | "wood";
export type PredefinedMode = "faces6" | "edges12" | "corners8" | "all26";
export type EdgeAxis = "top" | "bottom" | "left" | "right";
export type ImpactGridMode = "1x1" | "2x1" | "1x2" | "3x1" | "1x3" | "3x3";
export type ImpactLocationMode = "grid" | "percentage" | "random";
export type ImpactorType = "ball" | "cylinder";
export type CylinderDiameter = 8 | 15 | "custom";
export type CumDirection = `F${1 | 2 | 3 | 4 | 5 | 6}` | `E${1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12}` | `C${1 | 2 | 3 | 4 | 5 | 6 | 7 | 8}`;
export type ToleranceMode = "disabled" | "enabled";
export type ToleranceSettings = {
    mode: ToleranceMode;
    faceTolerance?: number;
    edgeTolerance?: number;
    cornerTolerance?: number;
};
export interface ScenarioRow {
    id: string;
    name: string;
    description?: string;
    fileName?: string;
    file?: File;
    objFileName?: string;
    objFile?: File;
    analysisType: AnalysisType;
    params?: {
        angleSource?: AngleSource;
        angleSourceId?: string;
        angleSourceFileName?: string;
        angleSourceFile?: File;
        heightMode?: HeightMode;
        heightConst?: number;
        heightMin?: number;
        heightMax?: number;
        surface?: SurfaceType;
        mbdCount?: number;
        faTotal?: number;
        includeFace6?: boolean;
        includeEdge12?: boolean;
        includeCorner8?: boolean;
        cumRepeatCount?: 2 | 3 | 4 | 5;
        cumDOECount?: number;
        cumDirections?: CumDirection[];
        cumDirectionsGrid?: CumDirection[][];
        multiRepeatCount?: number;
        multiRepeatDirections?: CumDirection[];
        piMode?: PartialImpactMode;
        piTxtName?: string;
        piTxtFile?: File;
        impactPackagePatterns?: string[];
        impactLocationMode?: ImpactLocationMode;
        impactGridMode?: ImpactGridMode;
        impactPercentageX?: number;
        impactPercentageY?: number;
        impactLocations?: Array<{
            x: number;
            y: number;
        }>;
        impactGridRows?: number;
        impactGridCols?: number;
        applyEdgeMargin?: boolean;
        impactPackageWidth?: number;
        impactPackageHeight?: number;
        impactRandomCount?: number;
        impactorType?: ImpactorType;
        impactorBallDiameter?: number;
        impactorCylinderDiameter?: CylinderDiameter | number;
        impactorCylinderDiameterCustom?: number;
        predefinedMode?: PredefinedMode;
        predefinedAngles?: Array<{
            name: string;
            phi: number;
            theta: number;
            psi: number;
        }>;
        edgeAxis?: EdgeAxis;
        edgeDivisions?: number;
        tolerance?: ToleranceSettings;
    };
}
declare const SimulationAutomationComponent: React.FC;
export default SimulationAutomationComponent;
